import { CallLog, Contact, SimConfig } from '../types';

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'c1',
    name: 'የኔ ዉድ❤️❤️❤️',
    number: '+251900253710',
    avatarLetter: 'የ',
    avatarColor: '#BA68C8', // Purple
    type: 'Mobile',
  },
  {
    id: 'c2',
    name: 'ኑሩ',
    number: '+251 97 353 5775',
    avatarLetter: 'ኑ',
    avatarColor: '#26C6DA', // Teal/Cyan
    type: 'Mobile',
  },
  {
    id: 'c3',
    name: 'መኪ የጀ',
    number: '094 292 4306',
    avatarLetter: 'መኪ',
    avatarColor: '#FBC02D', // Yellow/Gold
    type: 'Mobile',
  },
  {
    id: 'c4',
    name: 'ቆጂየዋ ሽካ',
    number: '+251990646897',
    avatarLetter: 'ቆ',
    avatarColor: '#EF9A9A', // Salmon
    type: 'Mobile',
  },
];

export const INITIAL_CALL_LOGS: CallLog[] = [
  {
    id: 'l1',
    number: '951',
    direction: 'outgoing',
    timestamp: '1 min ago',
    timeAgo: '1 min ago',
    dateGroup: 'Today',
    carrier: 'Ethio telecom',
    hasRecording: true,
  },
  {
    id: 'l2',
    number: '847',
    direction: 'outgoing',
    timestamp: '19 min ago',
    timeAgo: '19 min ago',
    dateGroup: 'Today',
    carrier: 'Ethio telecom',
    count: 3,
    hasRecording: true,
  },
  {
    id: 'l3',
    number: '841',
    direction: 'outgoing',
    timestamp: '20 min ago',
    timeAgo: '20 min ago',
    dateGroup: 'Today',
    carrier: 'Ethio telecom',
  },
  {
    id: 'l4',
    number: '847',
    direction: 'outgoing',
    timestamp: '21 min ago',
    timeAgo: '21 min ago',
    dateGroup: 'Today',
    carrier: 'Ethio telecom',
  },
  {
    id: 'l5',
    number: '951',
    direction: 'outgoing',
    timestamp: '44 min ago',
    timeAgo: '44 min ago',
    dateGroup: 'Today',
    carrier: 'Ethio telecom',
    hasRecording: true,
  },
  {
    id: 'l6',
    number: '951',
    direction: 'outgoing',
    timestamp: '46 min ago',
    timeAgo: '46 min ago',
    dateGroup: 'Today',
    carrier: 'Ethio telecom',
    hasRecording: true,
  },
  {
    id: 'l7',
    name: 'የኔ ዉድ❤️❤️❤️',
    number: '+251900253710',
    direction: 'outgoing',
    timestamp: '12:06 am',
    timeAgo: '12:06 am',
    dateGroup: 'Today',
    carrier: 'Ethio telecom',
    count: 2,
    avatarLetter: 'የ',
    avatarColor: '#BA68C8',
  },
  {
    id: 'l8',
    name: 'የኔ ዉድ❤️❤️❤️',
    number: '+251900253710',
    direction: 'outgoing',
    timestamp: 'Mon 11:24 pm',
    timeAgo: 'Mon 11:24 pm',
    dateGroup: 'Yesterday',
    carrier: 'Ethio telecom',
    count: 2,
    avatarLetter: 'የ',
    avatarColor: '#BA68C8',
  },
  {
    id: 'l9',
    name: 'የኔ ዉድ❤️❤️❤️',
    number: '+251900253710',
    direction: 'missed',
    timestamp: 'Mon 11:22 pm',
    timeAgo: 'Mon 11:22 pm',
    dateGroup: 'Yesterday',
    carrier: 'Ethio telecom',
    count: 2,
    avatarLetter: 'የ',
    avatarColor: '#BA68C8',
  },
  {
    id: 'l10',
    name: 'የኔ ዉድ❤️❤️❤️',
    number: '+251900253710',
    direction: 'outgoing',
    timestamp: 'Mon 10:39 pm',
    timeAgo: 'Mon 10:39 pm',
    dateGroup: 'Yesterday',
    carrier: 'Ethio telecom',
    avatarLetter: 'የ',
    avatarColor: '#BA68C8',
  },
  {
    id: 'l11',
    name: 'የኔ ዉድ❤️❤️❤️',
    number: '+251900253710',
    direction: 'incoming',
    timestamp: 'Mon 9:56 pm',
    timeAgo: 'Mon 9:56 pm',
    dateGroup: 'Yesterday',
    carrier: 'Ethio telecom',
    avatarLetter: 'የ',
    avatarColor: '#BA68C8',
  },
  {
    id: 'l12',
    name: 'የኔ ዉድ❤️❤️❤️',
    number: '+251900253710',
    direction: 'incoming',
    timestamp: 'Mon 4:57 pm',
    timeAgo: 'Mon 4:57 pm',
    dateGroup: 'Yesterday',
    carrier: 'Ethio telecom',
    avatarLetter: 'የ',
    avatarColor: '#BA68C8',
  },
];

export const INITIAL_SIMS: SimConfig[] = [
  {
    id: 1,
    name: 'Ethio telecom',
    color: '#00897B',
    badgeBg: '#00897B',
  },
  {
    id: 2,
    name: 'Ethio telecom',
    color: '#3949AB',
    badgeBg: '#3949AB',
  },
];
